name: DiscordChat
version: '1.0_Alpha'
main: com.soda9417.DiscordPlugin
api-version: 1.15
author: soda9417
commands:
  limitChannel:
    description: 디스코드와 연결될 채팅 채널을 제한합니다. 관리자만 사용할 수 있습니다.
    usage: 잘못된 형식입니다. /limitChannel [channels( separate with comma(,) )]
    aliases: [limchan,lim]
  discordMessage:
    description: 디스코드에 메시지를 보냅니다.
    usage: 잘못된 형식입니다. /discordMessage [message]
    aliases: [d,dm]
  toggleEffect:
    description: 알림 수신 등을 허용/차단합니다. 계정 연결 시, 본인의 계정이 멘션되면 플레이어에게도 알림이 갑니다.
    usage: 잘못된 형식입니다. /toggleEffect
    aliases: [te,mention]
  changeChannel:
    description: 채널을 변경합니다. 관리자인 경우 기본 채널 역시 변경됩니다.
    usage: 잘못된 형식입니다. /changeChannel [채널 이름]
    aliases: [channel,defaultChannel,chan]
  account:
    description: 디스코드 계정 관련 설정을 진행합니다. 계정 등록, 계정 정보 열람, 음성 채널 이동 등을 수행할 수 있습니다.
    usage: 잘못된 형식입니다. /account register [계정 이름]  /accout my_account /account move [이동할 음성 채널 이름]
    aliases: [acc]
